env: "local"
httpServer:
  address: "0.0.0.0"
  port: "8080"
  timeout: 5s
  secret: "secret"
socks5proxy:
  address: "0.0.0.0"
  port: "1080"
db:
  host: "localhost"
  port: "5432"
  name: "postgres"
  user: "postgres"
  password: "postgres"
bot:
  admins:
    - KrAssor
  tgbot_apitoken: 
  AI:
    timeout: 300
    #deepseek 
    #aiapitoken: 
    #openai
    # aiapitoken: 
    #openrouter
    aiapitoken: 
    systemRolePromt: 
    maxTokens: 4096
    temperature: 0.1
    n: 1
    baseURL: https://openrouter.ai/api/v1/
    modelName: cognitivecomputations/dolphin3.0-r1-mistral-24b:free
